name: PunchTree-Util
main: net.punchtree.util.PunchTreeUtilPlugin
version: 1.6.13
api-version: 1.20
description: Util libraries common to the whole network

libraries:
    - org.jetbrains.kotlin:kotlin-stdlib:1.9.22

commands:
    debugvar:
        aliases: dv
        usage: /debugvar <help|get|set|list>
        permission: punchtree.debugvar
        permission-message: You don't have permission to work with debug variables!
    cmd:
        permission: punchtree.admin
    playingcards:
        description: A catchall command for playing cards stuff
        usage: /playingcards <subcommand>
        permission: punchtree.in-progress-testing.playing-cards
        aliases: [ pc ]
    soundtest:
        usage: "/soundtest [page #]"
        aliases: st
        description: Browse minecraft sounds with /st [page #]
        permission: punchtree.soundtest
    placementtool:
        usage: /placementtool [on|off]
        aliases: [ pmt ]
        permission: punchtree.admin.placementtool
    interactionplacementtool:
        usage: /interactionplacementtool [help]
        aliases: [ ipmt ]
        permission: punchtree.admin.interactionplacementtool
    interactiontagtool:
        usage: /interactiontagtool [help]
        aliases: [ itt ]
        permission: punchtree.admin.interactiontagtool
    utilikill:
        usage: /utilikill <tag> [max distance] [type]
        aliases: [ uk ]
        permission: punchtree.admin.utilikill
    visualize:
        usage: /visualize <subcommand(s)>
        aliases: [ viz ]
        permission: punchtree.admin.visualize

permissions:
    punchtree.debugvar:
        default: false
    punchtree.admin:
        default: false
    punchtree.soundtest:
        default: true
