name: PunchTree-Util
main: net.punchtree.util.PunchTreeUtilPlugin
version: 1.3.4
api-version: 1.19
description: Util libraries common to the whole network

commands:
    debugvar:
        aliases: dv
        usage: /debugvar <help|get|set|list>
        permission: punchtree.debugvar
        permission-message: You don't have permission to work with debug variables!
    cmd:
        permission: punchtree.admin
    playingcards:
        description: A catchall command for playing cards stuff
        usage: /playingcards <subcommand>
        permission: punchtree.in-progress-testing.playing-cards
        aliases: [ pc ]

permissions:
    punchtree.debugvar:
        default: false
    punchtree.admin:
        default: false
